version: "3"
services:
    database:
        image: "postgres:10.4-alpine"
        environment:
            POSTGRES_USER: "api"
            POSTGRES_PASSWORD: "4qKxDhSN"
            POSTGRES_DB: "get4me"
    api:
        build: .
        volumes: 
            - .:/code
        working_dir: /code
        ports:
            - "8000:8000"
        depends_on:
            - "database"
        environment:
            DB_HOST: "database"
            DB_DATABASE: "get4me"
            DB_USER: "api"
            DB_PASSWORD: "4qKxDhSN"
            GMAPS_API_KEY: "AIzaSyBmwJLpVgjxyHQu6HK73-tNcCbhSz2MeIw"
        command: ["./wait-for-database.sh", "make", "run"]